#spring:
#  datasource:
#      driver-class-name: com.mysql.jdbc.Driver
#      username: root
#      password: root
#      url: jdbc:mysql://localhost:3306/sell?useUnicode=true&amp;characterEncoding=utf-8
#  redis:
#    host: 192.168.199.131
#    port: 6379
#    pool:
#      max-active: 1000
#      max-idle: 100
#      min-idle: 1
#  jpa:
#      show-sql: true
#  jackson:
#    default-property-inclusion: non_null
#logging:
#  pattern:
#    console: "%d - %msg%n"
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#
#
#
#
